apiVersion: apps/v1
kind: Deployment
metadata:
  name: reports-web-deployment
  namespace: bold-services
spec:
  selector:
    matchLabels:
      app: reports-web
  replicas: 1
  template:
    metadata:
      labels:
        app: reports-web
    spec:
      initContainers:
      - name: id-web-initialization
        image: busybox:1.28
        command: ["/bin/sh","-c"]
        args: ["if [ ! -f /application/app_data/configuration/config.xml ]; then echo waiting for id-web; sleep 5; else echo config.xml file exist; fi"]
        volumeMounts:
        - mountPath: /application/app_data
          name: reports-web-volume
      containers:
      - name: reports-web-container
        image: gcr.io/boldreports/boldreports-server:5.4.21_k0s
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 750Mi
          limits:
            cpu: 500m
            memory: 2Gi
        readinessProbe:
          httpGet:
            path: /health-check
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 10
        volumeMounts:
        - mountPath: /application/app_data
          name: reports-web-volume
        - mountPath: /application/reporting/web/logs
          name: log4net-config-volume
      volumes:
      - name: reports-web-volume
        persistentVolumeClaim:
          claimName: bold-fileserver-claim
          readOnly: false
      - name: log4net-config-volume
        configMap:
          name: log4net-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reports-api-deployment
  namespace: bold-services
spec:
  selector:
    matchLabels:
      app: reports-api
  replicas: 1
  template:
    metadata:
      labels:
        app: reports-api
    spec:
      initContainers:
      - name: id-web-initialization
        image: busybox:1.28
        command: ["/bin/sh","-c"]
        args: ["if [ ! -f /application/app_data/configuration/config.xml ]; then echo waiting for id-web; sleep 5; else echo config.xml file exist; fi"]
        volumeMounts:
        - mountPath: /application/app_data
          name: reports-api-volume
      containers:
      - name: reports-api-container
        image: gcr.io/boldreports/boldreports-server-api:5.4.21_k0s
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 750Mi
        readinessProbe:
          httpGet:
            path: /health-check
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 10
        volumeMounts:
        - mountPath: /application/app_data
          name: reports-api-volume
        - mountPath: /application/reporting/api/logs
          name: log4net-config-volume
      volumes:
      - name: reports-api-volume
        persistentVolumeClaim:
          claimName: bold-fileserver-claim
          readOnly: false
      - name: log4net-config-volume
        configMap:
          name: log4net-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reports-jobs-deployment
  namespace: bold-services
spec:
  selector:
    matchLabels:
      app: reports-jobs
  replicas: 1
  template:
    metadata:
      labels:
        app: reports-jobs
    spec:
      initContainers:
      - name: id-web-initialization
        image: busybox:1.28
        command: ["/bin/sh","-c"]
        args: ["if [ ! -f /application/app_data/configuration/config.xml ]; then echo waiting for id-web; sleep 5; else echo config.xml file exist; fi"]
        volumeMounts:
        - mountPath: /application/app_data
          name: reports-jobs-volume
      containers:
      - name: reports-jobs-container
        image: gcr.io/boldreports/boldreports-server-jobs:5.4.21_k0s
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 750Mi
          limits:
            cpu: 1000m
            memory: 2Gi
        readinessProbe:
          httpGet:
            path: /health-check
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 10
        volumeMounts:
        - mountPath: /application/app_data
          name: reports-jobs-volume
        - mountPath: /application/reporting/jobs/logs
          name: log4net-config-volume
      volumes:
      - name: reports-jobs-volume
        persistentVolumeClaim:
          claimName: bold-fileserver-claim
          readOnly: false
      - name: log4net-config-volume
        configMap:
          name: log4net-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reports-reportservice-deployment
  namespace: bold-services
spec:
  selector:
    matchLabels:
      app: reports-reportservice
  replicas: 1
  template:
    metadata:
      labels:
        app: reports-reportservice
    spec:
      initContainers:
      - name: id-web-initialization
        image: busybox:1.28
        command: ["/bin/sh","-c"]
        args: ["if [ ! -f /application/app_data/configuration/config.xml ]; then echo waiting for id-web; sleep 5; else echo config.xml file exist; fi"]
        volumeMounts:
        - mountPath: /application/app_data
          name: reports-reportservice-volume
      containers:
      - name: reports-reportservice-container
        image: gcr.io/boldreports/boldreports-designer:5.4.21_k0s
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 750Mi
          limits:
            cpu: 1000m
            memory: 2Gi
        readinessProbe:
          httpGet:
            path: /health-check
            port: 80
          initialDelaySeconds: 40
          periodSeconds: 10
        volumeMounts:
        - mountPath: /application/app_data
          name: reports-reportservice-volume
        - mountPath: /application/reporting/reportservice/logs
          name: log4net-config-volume
      volumes:
      - name: reports-reportservice-volume
        persistentVolumeClaim:
          claimName: bold-fileserver-claim
          readOnly: false
      - name: log4net-config-volume
        configMap:
          name: log4net-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reports-viewer-deployment
  namespace: bold-services
spec:
  selector:
    matchLabels:
      app: reports-viewer
  replicas: 1
  template:
    metadata:
      labels:
        app: reports-viewer
    spec:
      initContainers:
      - name: id-web-initialization
        image: busybox:1.28
        command: ["/bin/sh","-c"]
        args: ["if [ ! -f /application/app_data/configuration/config.xml ]; then echo waiting for id-web; sleep 5; else echo config.xml file exist; fi"]
        volumeMounts:
        - mountPath: /application/app_data
          name: reports-viewer-volume
      containers:
      - name: reports-viewer-container
        image: gcr.io/boldreports/boldreports-viewer:5.4.21_k0s
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 750Mi
          limits:
            cpu: 1000m
            memory: 2Gi
        readinessProbe:
          httpGet:
            path: /health-check
            port: 80
          initialDelaySeconds: 40
          periodSeconds: 10
        volumeMounts:
        - mountPath: /application/app_data
          name: reports-viewer-volume
        - mountPath: /application/reporting/viewer/logs
          name: log4net-config-volume
      volumes:
      - name: reports-viewer-volume
        persistentVolumeClaim:
          claimName: bold-fileserver-claim
          readOnly: false
      - name: log4net-config-volume
        configMap:
          name: log4net-config