apiVersion: v1
kind: Service
metadata:
  name: reports-web-service
  namespace: bold-services
  labels:
    app: reports-web
spec:
  type: NodePort
  ports:
  - name: reports-web-port
    port: 6550
    targetPort: 80
    protocol: TCP
  selector:
    app: reports-web
--- 
apiVersion: v1
kind: Service
metadata:
  name: reports-api-service
  namespace: bold-services
  labels:
    app: reports-api
spec:
  type: NodePort
  ports:
  - name: reports-api-port
    port: 6551
    targetPort: 80
    protocol: TCP
  selector:
    app: reports-api
---
apiVersion: v1
kind: Service
metadata:
  name: reports-jobs-service
  namespace: bold-services
  labels:
    app: reports-jobs
spec:
  type: NodePort
  ports:
  - name: reports-jobs-port
    port: 6552
    targetPort: 80
    protocol: TCP
  selector:
    app: reports-jobs
---
apiVersion: v1
kind: Service
metadata:
  name: reports-reportservice-service
  namespace: bold-services
  labels:
    app: reports-reportservice
spec:
  type: NodePort
  ports:
  - name: reports-reportservice-port
    port: 6553
    targetPort: 80
    protocol: TCP
  selector:
    app: reports-reportservice
---
apiVersion: v1
kind: Service
metadata:
  name: reports-viewer-service
  namespace: bold-services
  labels:
    app: reports-viewer
spec:
  type: NodePort
  ports:
  - name: reports-viewer-port
    port: 6554
    targetPort: 80
    protocol: TCP
  selector:
    app: reports-viewer