apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bold-services
resources:
  - ../boldbi-manifest

#Enter your GKS nfs Path and GKS nfs server 
patches:
  - target:
      kind: PersistentVolume
      name: bold-fileserver
    patch: |-
      - op: replace
        path: /spec/nfs/path
        value: "/<file_share_name>"
      - op: replace
        path: /spec/nfs/server
        value: "<file_share_ip_address>"

configMapGenerator:
- name: bold-bi-config
  namespace: bold-services
  literals:
  #Enter Your AppBase URL
    - APP_BASE_URL=<AppBase-URL>
    - BOLD_SERVICES_HOSTING_ENVIRONMENT=k8s
    - INSTALL_OPTIONAL_LIBS=mongodb,mysql,influxdb,snowflake,oracle,clickhouse,google
    - BOLD_SERVICES_USE_SITE_IDENTIFIER=true

- name: branding-config
  namespace: bold-services
  # All the branding images variables are accepted as URL.
  # Image type: png, svg, jpg, jpeg
  # Ex: https://example.com/loginlogo.jpg
  literals:
     # This is the header logo for the application, and the preferred image size is 40 x 40 pixels.
    - BOLD_SERVICES_BRANDING_MAIN_LOGO=

    # This is the login logo for the application, and the preferred image size is 200 x 40 pixels.
    - BOLD_SERVICES_BRANDING_LOGIN_LOGO=

    # This is an email logo, and the preferred image size is 200 x 40 pixels.
    - BOLD_SERVICES_BRANDING_EMAIL_LOGO= 

    # This is a favicon, and the preferred image size is 40 x 40 pixels.
    - BOLD_SERVICES_BRANDING_FAVICON=

    # This is powered by the logo, and the preferred size is 100 x 25 pixels.
    - BOLD_SERVICES_BRANDING_FOOTER_LOGO=

     # This is organization name.
    - BOLD_SERVICES_SITE_NAME=

    # This is site identifier, and it will be the part of the application URL.
    - BOLD_SERVICES_SITE_IDENTIFIER=
  # Note: If you want to use the custom branding, provide the value for all branding variables 
  # If all variable values are given, application will use the branding images,
  # otherwise it will take the default logos.

- name: version-config
  namespace: bold-services
  literals:
    - BOLD_SERVICES_BI_API_VERSION=7.4.11 
    - BOLD_SERVICES_BI_DESIGNER_VERSION=7.4.11 
    - BOLD_SERVICES_BI_JOBS_VERSION=7.4.11 
    - BOLD_SERVICES_BI_WEB_VERSION=7.4.11 
    - BOLD_SERVICES_ID_API_VERSION=7.4.11 
    - BOLD_SERVICES_ID_WEB_VERSION=7.4.11 
    - BOLD_SERVICES_UMS_WEB_VERSION=7.4.11 
    - BOLD_SERVICES_BI_ETL_VERSION=7.4.11 

secretGenerator:
- name: bold-secret
  namespace: bold-services
  literals:
  - widget_bing_map_enable_secret=
  - widget_bing_map_api_key_secret=

- name: bold-user-secret
  namespace: bold-services
  literals:
  # It should be a valid email.
  - BOLD_SERVICES_USER_EMAIL=

  # It should meet our password requirements.
  - BOLD_SERVICES_USER_PASSWORD=

- name: bold-db-secret
  namespace: bold-services
  literals:
  # Type of database server can be used for configuring the Bold BI. Eg: mssql, mysql and postgresql
  - BOLD_SERVICES_DB_TYPE=

  # Name of the Database Server
  - BOLD_SERVICES_DB_HOST=

  # The system will use the following default port numbers based on the database server type.
  # PostgrSQL – 5234 and MySQL -3306
  # Please specify the port number for your database server if it is configured on a different port.
  # For MS SQL Server, this parameter is not necessary.
  - BOLD_SERVICES_DB_PORT=

  # Username for the database server
  # Please refer to this documentation for information on the user's permissions.
  # https://help.boldbi.com/embedded-bi/faq/what-are-the-database-permissions-required-to-set-up-bold-bi-embedded/
  - BOLD_SERVICES_DB_USER=

  # The database user's password
  - BOLD_SERVICES_DB_PASSWORD=

  # If the database name is not specified, the system will create a new database called bold services.
  # If you specify a database name, it should already exist on the server.
  - BOLD_SERVICES_DB_NAME=

  # For PostgreSQL DB Servers, this is an optional parameter.
  # The system will use the database name postgres by default.
  # If your database server uses a different default database, please provide it here.
  - BOLD_SERVICES_POSTGRESQL_MAINTENANCE_DB=

  # If your database server requires additional connection string parameters, include them here
  # Connection string parameters can be found in the official document.
  # My SQL: https://dev.mysql.com/doc/connector-net/en/connector-net-8-0-connection-options.html
  # PostgreSQL: https://www.npgsql.org/doc/connection-string-parameters.html
  # MS SQL: https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlconnection.connectionstring
  # Note: A semicolon(;) should be used to separate multiple parameters.
  - BOLD_SERVICES_DB_ADDITIONAL_PARAMETERS=

- name: bold-license-key
  namespace: bold-services
  literals:
  #  The Bold BI licnece key which you have purchesed.
  - BOLD_SERVICES_UNLOCK_KEY=
images:
  - name: gcr.io/boldbi-294612/boldbi-server-api
    newTag: 7.4.11 

  - name: gcr.io/boldbi-294612/boldbi-server-jobs
    newTag: 7.4.11

  - name: gcr.io/boldbi-294612/boldbi-server
    newTag: 7.4.11

  - name: gcr.io/boldbi-294612/boldbi-designer
    newTag: 7.4.11

  - name: gcr.io/boldbi-294612/bold-etl
    newTag: 7.4.11

  - name: gcr.io/boldbi-294612/bold-identity-api
    newTag: 7.4.11

  - name: gcr.io/boldbi-294612/bold-ums
    newTag: 7.4.11

  - name: gcr.io/boldbi-294612/bold-identity
    newTag: 7.4.11
generatorOptions:
  disableNameSuffixHash: true